name: Deploy

on: [ pull_request, push ]

jobs:
  job:
    name: Deploy
    runs-on: ubuntu-latest
    
    # CWD: github/github

    steps:
    - name: Checkout ShineyDev/github
      uses: actions/checkout@v2
      with:
        path: github
    
    # CWD: github/github/github

    - name: Checkout ShineyDev/docs
      uses: actions/checkout@v2
      with:
        path: docs
        repository: ShineyDev/docs

    # CWD: github/github/docs

    - name: Move
      run: cd ../github

    # CWD: github/github/github

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        python -m pip install --upgrade .[docs]

    - name: Move
      run: cd ..

    # CWD: github/github

    - name: Build documentation
      if: ${{ github.event_name == 'push' }}
      run: python -m sphinx -b html -a -E -n -T -W --keep-going ./${{ github.event.repository.name }}/docs ./docs/${{ github.event.repository.name }}/latest

    - name: Build documentation
      if: ${{ github.event_name == 'pull_request' }}
      run: python -m sphinx -h html -a -E -n -T -W --keep-going ./${{ github.event.repository.name }}/docs ./docs/${{ github.event.repository.name }}/pull/${{ github.event.pull_request.number }}

    - name: Move
      run: cd docs
  
    # CWD: github/github/docs

    - name: Push
      continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      run: |
        git config user.name github-actions[bot]
        git config user.password ${{ secrets.DOCS_TOKEN }}
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "update docs for ${{ github.repository }}@${{ github.sha }}"
        git push

    - name: Push
      continue-on-error: true
      if: ${{ github.event_name =='pull_request' }}
      run: |
        git config user.name github-actions[bot]
        git config user.password ${{ secrets.DOCS_TOKEN }}
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "create docs for ${{ github.repository }}#{{ github.event.pull_request.number }}@${{ github.sha }}"
        git push

    - name: Comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            ...context.repo,
            body: `Hey there! I'm a robot.\nI've built the [documentation for this pull request](https://shineydev.github.io/docs/${context.repo.name}/pull/${context.payload.pull_request.number}) for you.`,
            issue_number: context.payload.pull_request.number
          }))
